### ISSUE TITLE
Re-enable ocaml-ci 

### ISSUE THREAD

**Issue by tmcgilchrist** [dialohq/ocaml-grpc#23]
ocaml-ci was following this project when it was on @jeffa5's account.  Now that it has moved the build is no longer working. ocaml-ci is an opinionated CI system for OCaml projects using dune and opam. It provides multi-version and multi-platform builds for OCaml, many often not available on other CI platforms, that closely aligns with the opam-repository CI system. 

I've created a PR https://github.com/ocurrent/ocaml-ci/pull/769 to enable ocaml-ci on @dialohq. If you agree I can merge the PR and restore the CI functionality. You would need to install the GitHub App as documented [here](https://ci.ocamllabs.io/getting-started).

Please let me know if there are further questions about how to enable ocaml-ci or how ocaml-ci works.

**Comment by quernd** [comment]
Thank you @tmcgilchrist, this sounds great! The recent submission to opam-repository uncovered some build failures, so ocaml-ci will be extremely helpful. I have installed the GitHub app, so you're good to go. Thanks again!

**Comment by tmcgilchrist** [comment]
@quernd builds are showing up here https://ci.ocamllabs.io/github/dialohq/ocaml-grpc. I've also opened  https://github.com/dialohq/ocaml-grpc/pull/24 with some CI fixes.
