### ISSUE TITLE
no incremental display in routeguide-client

### ISSUE THREAD

**Issue by aryx** [dialohq/ocaml-grpc#60]
I followed the instructions in https://github.com/dialohq/ocaml-grpc/blob/main/examples/routeguide-tutorial.md

and run `dune exec -- routeguide-server ./examples/routeguide/data/route_guide_db.json`
in one terminal and
`dune exec -- routeguide-client`
in another one, but as opposed to the documentation that says the client will show response from the streaming server
one second at a time, instead I get all the results at the very end
in one block.

I'm running the example from the ocaml-grpc repository, with eio 1.0 and OCaml 5.2.0
on arch linux.
```
 opam list | grep eio
eio                        1.0              Effect-based direct-style IO API for OCaml
eio_linux                  1.0              Eio implementation for Linux using io-uring
eio_main                   1.0              Effect-based direct-style IO mainloop for OCaml
eio_posix                  1.0              Eio implementation for POSIX systems
gluten-eio                 0.5.0            EIO runtime for gluten
grpc-eio                   0.2.0            An Eio implementation of gRPC
h2-eio                     0.11.0           EIO support for h2
[pad@thinkstation ocaml-grpc (main)]$ ocamlc -v
The OCaml compiler, version 5.2.0
Standard library directory: /home/pad/.opam/5.2.0/lib/ocaml

```

**Comment by wokalski** [comment]
This is fixed in #56

**Comment by aryx** [comment]
Do you have a timeline for where your reimplementation will be finished @wokalski ?

**Comment by wokalski** [comment]
I'm afraid I don't. It's already used in production but there's still stuff I'd like to improve. In more than 2 weeks and less than 1 month I'll be using it very extensively again in a work project and I'll likely finish the reimpl off then.

**Comment by aryx** [comment]
ok great!
